server:
  port: 8082
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/payment-service-db
    username: postgres
    password: chamilaRoot@123

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:29092

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [corrId=%X{correlationId}] %-5level %logger - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: always