server:
  port: 8080
#  servlet:
#    context-path: /api/v1

spring:
  application:
    name: user-service



#   1. Database Connection Settings
  datasource:
    url: jdbc:postgresql://postgres:5432/userservice_db
    username: postgres
    password: postgres


  # Global JPA configurations (Dialect, naming strategies, etc.)
  jpa:
    open-in-view: false # Production performance best practice (prevents connection leaks)
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Global Flyway configurations
  flyway:
    locations: classpath:db/migration


#debug: true



