create table roles (id bigint generated by default as identity, role varchar(255), primary key (id));
create table user_role (role_id bigint not null, user_id bigint not null);
create table users (account_expired boolean not null, account_non_locked boolean not null, credentials_non_expired boolean not null, dob date, enabled boolean not null, id bigint generated by default as identity, public_id uuid, email varchar(255) not null unique, first_name varchar(255), last_name varchar(255), password varchar(255) not null, primary key (id));
alter table if exists user_role add constraint FKt7e7djp752sqn6w22i6ocqy6q foreign key (role_id) references roles;
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users;
